#!/bin/sh
#
# $NetBSD: qmailsmtpssld.sh,v 1.7 2016/06/01 21:06:39 thomaslazar $
# based on $NetBSD: qmailsmtpd.sh,v 1.7 2005/07/19 21:06:39 schmonz Exp $
#
# qmail-run-20060604 script to control qmail-smtpd (SMTP service).
#

# PROVIDE: qmailsmtpssld mail
# REQUIRE: qmailsend

name="qmailsmtpssld"

# User-settable rc.conf variables and their default values:
: ${qmailsmtpssld_postenv:="QMAILQUEUE=/usr/pkg/bin/qmail-queue CERTFILE=/var/qmail/control/servercert.pem KEYFILE= DHFILE= "}
: ${qmailsmtpssld_tcpflags:="-vRl0"}
: ${qmailsmtpssld_tcphost:="0"}
: ${qmailsmtpssld_tcpport:="465"}
: ${qmailsmtpssld_datalimit:="2000000"}
: ${qmailsmtpssld_pretcpserver:=""}
: ${qmailsmtpssld_presmtpd:=""}
: ${qmailsmtpssld_postsmtpd:=""}
: ${qmailsmtpssld_log:="YES"}
: ${qmailsmtpssld_logcmd:="logger -t nb${name} -p mail.info"}
: ${qmailsmtpssld_nologcmd:="/usr/pkg/bin/multilog -*"}

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
fi

rcvar=${name}
required_files="/usr/pkg/etc/qmail/control/concurrencyincoming"
required_files="${required_files} /usr/pkg/etc/qmail/tcp.smtp.cdb"
required_files="${required_files} /usr/pkg/etc/qmail/control/rcpthosts"
command="/usr/pkg/bin/sslserver"
procname=${name}
start_precmd="qmailsmtpssld_precmd"
extra_commands="stat pause cont cdb"
stat_cmd="qmailsmtpssld_stat"
pause_cmd="qmailsmtpssld_pause"
cont_cmd="qmailsmtpssld_cont"
cdb_cmd="qmailsmtpssld_cdb"

qmailsmtpssld_precmd()
{
	# sslserver is akin to inetd(8), but runs one service per process.
	# We want to signal only the sslserver process responsible for SMTP
	# service. Use argv0(1) to set procname to "qmailsmtpssld".
	if [ -f /etc/rc.subr ]; then
		checkyesno qmailsmtpssld_log || qmailsmtpssld_logcmd=${qmailsmtpssld_nologcmd}
	fi
	command="/usr/bin/env - ${qmailsmtpssld_postenv} /usr/pkg/bin/softlimit -m ${qmailsmtpssld_datalimit} ${qmailsmtpssld_pretcpserver} /usr/pkg/bin/argv0 /usr/pkg/bin/sslserver ${name} -e ${qmailsmtpssld_tcpflags} -x /usr/pkg/etc/qmail/tcp.smtp.cdb -c `/usr/bin/head -1 /usr/pkg/etc/qmail/control/concurrencyincoming` -u `/usr/bin/id -u qmaild` -g `/usr/bin/id -g qmaild` ${qmailsmtpssld_tcphost} ${qmailsmtpssld_tcpport} ${qmailsmtpssld_presmtpd} /usr/pkg/bin/qmail-smtpd ${qmailsmtpssld_postsmtpd} 2>&1 | /usr/pkg/bin/setuidgid qmaill ${qmailsmtpssld_logcmd}"
	command_args="&"
	rc_flags=""
}

qmailsmtpssld_stat()
{
	run_rc_command status
}

qmailsmtpssld_pause()
{
	if ! statusmsg=`run_rc_command status`; then
		echo $statusmsg
		return 1
	fi
	echo "Pausing ${name}."
	kill -STOP $rc_pid
}

qmailsmtpssld_cont()
{
	if ! statusmsg=`run_rc_command status`; then
		echo $statusmsg
		return 1
	fi
	echo "Continuing ${name}."
	kill -CONT $rc_pid
}

qmailsmtpssld_cdb()
{
	echo "Reloading /usr/pkg/etc/qmail/tcp.smtp."
	/usr/pkg/bin/tcprules /usr/pkg/etc/qmail/tcp.smtp.cdb /usr/pkg/etc/qmail/tcp.smtp.tmp < /usr/pkg/etc/qmail/tcp.smtp
	/bin/chmod 644 /usr/pkg/etc/qmail/tcp.smtp.cdb
}

if [ -f /etc/rc.subr ]; then
	load_rc_config $name
	run_rc_command "$1"
else
	echo -n " ${name}"
	qmailsmtpssld_precmd
	eval ${command} ${qmailsmtpssld_flags} ${command_args}
fi
